/*ALTER TABLE EMPLOYEE ADD COLUMN SALARY INT;
ALTER TABLE EMPLOYEE ADD COLUMN ROLE TEXT;
ALTER TABLE EMPLOYEE ADD COLUMN JOB_LOCATION TEXT;
*/

SELECT * FROM EMPLOYEE;
UPDATE Employee
SET
    SALARY = (
        SELECT SALARY
        FROM Job_Info
        WHERE Job_Info.EMPLOYEE_ID = Employee.ID
    ),
    ROLE = (
        SELECT ROLE
        FROM Job_Info
        WHERE Job_Info.EMPLOYEE_ID = Employee.ID
    ),
    JOB_LOCATION = (
        SELECT JOB_LOCATION
        FROM Job_Info
        WHERE Job_Info.EMPLOYEE_ID = Employee.ID
    );