SELECT
    EMPLOYEE.ID,
    EMPLOYEE.FIRST_NAME,
    EMPLOYEE.LAST_NAME,
    EMPLOYEE.DATE,
    EMPLOYEE.EDUCATION,
    JOB_INFO.SALARY,
    JOB_INFO.ROLE,
    JOB_INFO.JOB_LOCATION
FROM EMPLOYEE
INNER JOIN JOB_INFO
ON EMPLOYEE.ID = JOB_INFO.EMPLOYEE_ID;