ALTER TABLE EMPLOYEE ADD COLUMN EMAIL VARCHAR;
ALTER TABLE EMPLOYEE ADD COLUMN PHONE_NUMBER VARCHAR;
ALTER TABLE EMPLOYEE ADD COLUMN ADDRESS VARCHAR;
ALTER TABLE EMPLOYEE ADD COLUMN ZIP_CODE INT; 
ALTER TABLE EMPLOYEE ADD COLUMN EMERGENCY_CONTACT TEXT;


SELECT * FROM EMPLOYEE;

UPDATE Employee
SET
    EMAIL = (
        SELECT EMAIL
        FROM Contact_Info
        WHERE Contact_Info.EMPLOYEE_ID = Employee.ID
    ),
    PHONE_NUMBER = (
        SELECT PHONE_NUMBER
        FROM Contact_Info
        WHERE Contact_Info.EMPLOYEE_ID = Employee.ID
    ),
    ADDRESS = (
        SELECT ADDRESS
        FROM Contact_Info
        WHERE Contact_Info.EMPLOYEE_ID = Employee.ID
    ),
    ZIP_CODE = (
        SELECT ZIP_CODE
        FROM Contact_Info
        WHERE Contact_Info.EMPLOYEE_ID = Employee.ID
    ),
    EMERGENCY_CONTACT = (
        SELECT EMERGENCY_CONTACT
        FROM Contact_Info
        WHERE Contact_Info.EMPLOYEE_ID = Employee.ID
    );
